apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: default
  labels:
    app: sqlserver
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: sqlserver
  selector:
    app: sqlserver
  clusterIP: None # Headless service for StatefulSet
