apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

# namePrefix: dev-

labels:
  - pairs:
      environment: dev

# Image tags for dev environment
images:
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/config-server
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/api-gateway
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/authentication-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/hr-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/inventory-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/finance-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/user-management-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/reporting-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/frontend
    newTag: dev-latest

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-hpa.yaml
  - path: monitoring-patch.yaml

configMapGenerator:
  - name: environment-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG
