apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - configmap-datasources.yaml
  - configmap-dashboards.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
