ConnectionStrings:
  DefaultConnection: Server=sqlserver,1433;Database=Konecta_Auth;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;

RabbitMq:
  HostName: rabbitmq
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  EmployeeCreatedQueue: auth.employee-created
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  UserProvisionedRoutingKey: auth.user.provisioned
  UserDeactivatedRoutingKey: auth.user.deactivated
  UserResignedRoutingKey: auth.user.resigned
  UserTerminatedRoutingKey: auth.user.terminated

Email:
  FromAddress: no-reply@konecta.local
  FromDisplayName: Konecta HR
  SmtpHost: ${SMTP_HOST:mailhog}
  SmtpPort: ${SMTP_PORT:1025}
  UseSsl: false
  UserName: ""
  Password: ""

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  ExpirationMinutes: 60
  RefreshTokenExpirationDays: 7
  Keys:
    - Id: key-202501
      IsCurrent: true
      PrivateKeyPem: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDcde425D/SHmX/
        FLZL1N/gb4l9qf/LP6xefkKwe9/UY1t1kEO1CIsIdNK4F1hHfDwggHKs6QGBNf8n
        zsIusUY8Z9PmmsZypSaYBmvzKPOD+VJGiZezEtgKUNSZyBg8+POwu0ZxB/9XCKZx
        9Ay5Ju0/PoRNcxp5zu3e51zAVbgM5zgU3b+9nrHT8LtIIcgzBquFXR5N/RdM0zQq
        XoEpnak33BayTYnxEuYoJEwa6UWJsJQd8G7d9Ke1NcOB9ZZHztEwXV3T6eeqFS5K
        Pne/djWVZLbYlL7mVvrxLf4Na/NYgLAtD0o8BKiFd5OYmFXFCHqYbIZyF1679pd1
        JAGGDDQdAgMBAAECggEACwDb1eOIh+06fAPFoX1Le0E15I7ClJtl+AVnQLW+EzSu
        UOzVZEi7370s80E/B7pcqeafUqACkjdmt87rBDeW4NbxzZW2B+zUQ0w2wRkvJkwg
        XiLp7mcnX0RviAljpE9sokqGloemp+pnnFJo/CjEOJ7fLZpsHN5GIxT7HSJqIEKm
        XI3b+izqS3uXC2kRtZSCjg3l5I9JdhZE/1Br/kKW7l6CN9/M01u6isbbk/cvsk9H
        ak7v0RuRWpdDR6PvwKjBEomsWJ50xE3YoqLH57lnTjualO0deuBr7H1PDe7HRo/u
        5FyKtgbk13t9CgbVrsWAofJQSajUzjNssdO06FxgxQKBgQD5nId0okx62xOp/VYX
        pyt1v+gzeeINQeu8iRGUndD0Xirb++5hSg7Zyb8Gs8DSmsSJ35IcLACiGcMP6bfs
        t/b8P3VQAJUHiB96ZbBpfclL1/il0QdTW0WZLSIhCaDQvEDDwF4fCgyWLUg65bNW
        WUM2dDe08hLQQ5/lClxvoW06qwKBgQDiGmdQMO4oOjj8ZVFuwQ7ugeE8+CvJNgxm
        rfJFUmMJJLZtUaUmXtA+4y1xAnOHtmrtPXrhIZrsAKw8QBllRPvGmJEcwEAvCoLR
        DB+paeD0uawtyfuVVithibjIfamzSv7t43ZPEtnfSYYZk/2EV+CMa/pqWdDdv55k
        /qqODYfMVwKBgH0tVHjXU4dhClF7bItcGF1qqiX2f7iqUHAyRRDEvB9wggnkI73C
        iAQMOrI/vvlfCCUka3+ZSZABX2NBkC00bLY/lLNUN2iZiT+2c2vT2vkgC+AMHaJd
        6V9R1QXAcFd9sPT6KbljLsC5YLm4q+Enzp8mVTF3HJw47ZzNP2H0EHUVAoGBAIwv
        JKkCfVZxqs1KIDAUAKb93eGIWNV67jtnU9OJHiAYJAcpXMSqemDTR2ROycR15FvN
        B3e39y6lyCPe9h/kolniU+5IgELqOGtWIfdOzwvMZqVJGvPfJixmUCv2RZYFRIPH
        yJ2EKZMYKc2IBOHd/jnx5KO1phsmaBVkE+jZGL4nAoGAU1fL1x5j3N5svobstF2F
        7TRTwBYkGuGXD/O40Sw9Hf8GxfxVVtb/T1D0aypp5v+izCTcgBx6A3IT9Z4HAXSn
        uLUYCipMLPV/TKsNwEakuwoYW3ul5GqvpsY4/vLauZ5IBFl/HDHqx4YAYcCYvwze
        lsaKdwjH29NcnakM+FYMkyc=
        -----END PRIVATE KEY-----
      PublicKeyPem: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3HXuNuQ/0h5l/xS2S9Tf
        4G+Jfan/yz+sXn5CsHvf1GNbdZBDtQiLCHTSuBdYR3w8IIByrOkBgTX/J87CLrFG
        PGfT5prGcqUmmAZr8yjzg/lSRomXsxLYClDUmcgYPPjzsLtGcQf/VwimcfQMuSbt
        Pz6ETXMaec7t3udcwFW4DOc4FN2/vZ6x0/C7SCHIMwarhV0eTf0XTNM0Kl6BKZ2p
        N9wWsk2J8RLmKCRMGulFibCUHfBu3fSntTXDgfWWR87RMF1d0+nnqhUuSj53v3Y1
        lWS22JS+5lb68S3+DWvzWICwLQ9KPASohXeTmJhVxQh6mGyGchdeu/aXdSQBhgw0
        HQIDAQAB
        -----END PUBLIC KEY-----
    - Id: key-202412
      IsCurrent: false
      PublicKeyPem: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwzryUa4PxCak9GFT08xM
        39JPHR9E902kl96Gs3qLPBgWuXG0nC5cMi0vf25O06JLwV+WTDB6kdVPHyeOqr4G
        2y3vRUVoiaPhMqU6rj7rwj2J7hMCqtYhTgOSlIankqs7Khta3gT4ggIJYLiY93V7
        Gt8bdZ9cX1mmnNy7ZHCCgE0KPk+HuuBT7FrNBZvXheiblKOv3E7l5dFQbhmA6eu3
        085385oq/Zl1gEpQjR3dR7GRHO+6JPZ7wZT4eHjWBOVGOFBUvqdxIxgjc5WTV1Qx
        aDnzwJbdKHUNzlnl+m6dTBVIP6Hxww0W9Z2e2GtPy4GANgXn7GFFDvcr67iz43aU
        7QIDAQAB
        -----END PUBLIC KEY-----

ServiceAuth:
  SharedSecret: KonectaSharedSecret!
  UserManagementBaseUrl: http://user-management-service:5078

Consul:
  Host: http://consul-server:8500

ServiceConfig:
  ServiceName: authentication-service
  Host: 0.0.0.0
  PublicHost: authentication-service
  Port: 7280
  Scheme: http
  RegisterWithConsul: true
  FailFast: false
