ConnectionStrings:
  DefaultConnection: Server=sqlserver,1433;Database=Konecta_Auth;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;

RabbitMq:
  HostName: rabbitmq
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  CompensationEventsQueue: finance.compensation.events
  CompensationProvisionedRoutingKey: finance.compensation.provisioned
  CompensationBonusesRoutingKey: finance.compensation.bonuses
  CompensationDeductionsRoutingKey: finance.compensation.deductions

Consul:
  Host: http://consul-server:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: ${AUTH_JWKS_URI:http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: finance-service
  Host: 0.0.0.0
  PublicHost: finance-service
  Port: 5003
  RegisterWithConsul: true
  FailFast: false
