ConnectionStrings:
  DefaultConnection: Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;

RabbitMq:
  HostName: ${RABBITMQ_HOST:rabbitmq}
  Port: ${RABBITMQ_PORT:5672}
  UserName: ${RABBITMQ_USER:guest}
  Password: ${RABBITMQ_PASS:guest}
  VirtualHost: /
  Exchange: konecta.erp
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  FinanceCompensationProvisionedRoutingKey: finance.compensation.provisioned
  FinanceCompensationBonusesRoutingKey: finance.compensation.bonuses
  FinanceCompensationDeductionsRoutingKey: finance.compensation.deductions
  UserProvisionedQueue: hr.user-provisioned
  UserProvisionedRoutingKey: auth.user.provisioned

Consul:
  Host: ${CONSUL_URI}

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: ${AUTH_JWKS_URI:http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: hr-service
  Host: 0.0.0.0
  PublicHost: ${PUBLIC_HOST:hr-service}
  Port: 5005
  RegisterWithConsul: true
  FailFast: false
