ConnectionStrings:
  DefaultConnection: Server=sqlserver,1433;Database=Konecta_Auth;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;

RabbitMq:
  HostName: rabbitmq
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  FinanceCompensationProvisionedRoutingKey: finance.compensation.provisioned
  FinanceCompensationBonusesRoutingKey: finance.compensation.bonuses
  FinanceCompensationDeductionsRoutingKey: finance.compensation.deductions
  UserProvisionedQueue: hr.user-provisioned
  UserProvisionedRoutingKey: auth.user.provisioned

Consul:
  Host: http://consul-server:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://authentication-service:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: hr-service
  Host: 0.0.0.0
  PublicHost: hr-service
  Port: 5005
  RegisterWithConsul: true
  FailFast: false
