ConnectionStrings:
  DefaultConnection: Server=sqlserver,1433;Database=Konecta_Auth;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;

Consul:
  Host: http://consul-server:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: inventory-service
  Host: 0.0.0.0
  PublicHost: inventory-service
  Port: 5020
  RegisterWithConsul: true
  FailFast: false
