ConnectionStrings:
  DefaultConnection: Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;

Consul:
  Host: ${CONSUL_URI}

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: ${AUTH_JWKS_URI:http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: inventory-service
  Host: 0.0.0.0
  PublicHost: ${PUBLIC_HOST:inventory-service}
  Port: 5020
  RegisterWithConsul: true
  FailFast: false
