ConnectionStrings:
  DefaultConnection: Server=sqlserver,1433;Database=Konecta_UserManagement;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;

RabbitMq:
  HostName: rabbitmq
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  UserEventsQueue: user-management.user-events
  UserProvisionedRoutingKey: auth.user.provisioned
  UserDeactivatedRoutingKey: auth.user.deactivated
  UserResignedRoutingKey: auth.user.resigned
  UserTerminatedRoutingKey: auth.user.terminated

Consul:
  Host: http://consul-server:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://authentication-service:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceAuth:
  SharedSecret: KonectaSharedSecret!

ServiceConfig:
  ServiceName: user-management-service
  Host: 0.0.0.0
  PublicHost: user-management-service
  Port: 5078
  RegisterWithConsul: true
  FailFast: false
