ConnectionStrings:
  DefaultConnection: Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;

RabbitMq:
  HostName: ${RABBITMQ_HOST:rabbitmq}
  Port: ${RABBITMQ_PORT:5672}
  UserName: ${RABBITMQ_USER:guest}
  Password: ${RABBITMQ_PASS:guest}
  VirtualHost: /
  Exchange: konecta.erp
  UserEventsQueue: user-management.user-events
  UserProvisionedRoutingKey: auth.user.provisioned
  UserDeactivatedRoutingKey: auth.user.deactivated
  UserResignedRoutingKey: auth.user.resigned
  UserTerminatedRoutingKey: auth.user.terminated

Consul:
  Host: ${CONSUL_URI}

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: ${AUTH_JWKS_URI:http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceAuth:
  SharedSecret: ${SHARED_SECRET:KonectaSharedSecret!}

ServiceConfig:
  ServiceName: user-management-service
  Host: 0.0.0.0
  PublicHost: ${PUBLIC_HOST:user-management-service}
  Port: 5078
  RegisterWithConsul: true
  FailFast: false
