apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: konecta-erp-cert
  namespace: default
spec:
  domains:
    - your-domain.com # Replace with your actual domain
    # - www.your-domain.com
