apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konecta-erp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.global-static-ip-name: "konecta-erp-ingress-ip"
    # networking.gke.io/managed-certificates: "konecta-erp-cert"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.paths: "/api(/|$)(.*)"
  labels:
    app: konecta-erp
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

          - path: /swagger/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
