apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: default
  labels:
    app: authentication-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 7280
      targetPort: 7280
      protocol: TCP
      name: http
  selector:
    app: authentication-service
