# Deploy config-server Service to GCP Cloud Run
name: Deploy config-server Service
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "konecta_erp/backend/config/**"
      - ".github/workflows/deploy-config-server-service.yml"

env:
  IMAGE_NAME: "${{secrets.REPO_URL}}/config-server-service"

jobs:
  build and Push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build Docker Image
        working-directory: ./konecta_erp
        run: |
          docker build -f backend/config/Dockerfile -t ${{env.IMAGE_NAME}}:${{github.sha}} ./backend/config

      - name: Push Image
        run: docker push ${{env.IMAGE_NAME}}:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        working-directory: ./Terraform/services/config-server-service
        run: |
          terraform init
      # 4️⃣ Terraform Plan
      - name: Terraform Plan
        id: plan
        working-directory: ./Terraform/services/config-server-service
        run: |
          terraform plan \
            -var="image_tag=${{ env.IMAGE_NAME }}:${{ github.sha }}"

      # 5️⃣ Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./Terraform/services/config-server-service
        run: |
          terraform apply -auto-approve \
            -var="image_tag=${{ env.IMAGE_NAME }}:${{ github.sha }}"
